spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: "http://192.168.81.110:5000"
  application:
    name: config-client
  cloud:
    config:
      fail-fast: true
      discovery:
        enabled: true
#        service-id: config-server #需要注册中心的支持
      uri: http://192.168.81.110:8767 #不需要注册中心支持
      name: 13 #如果是其他yml，写全名即可，这里的13代表application-13.yml(也代表13.yml)
  rabbitmq:
    host: 192.168.81.31
    port: 5672
    username: admin
    password: MECT888!
server:
  port: 8766
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.81.110
  client:
    # 向注册中心注册
    fetch-registry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.81.110:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: "logs/${spring.application.name}.log"