eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    ip-address: 192.168.137.73
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    # 向注册中心注册
    fetch-registry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.137.73:8761/eureka/
server:
  port: 8762

spring:
  boot:
    admin:
      client:
        url: "http://192.168.137.73:5000"