eureka:
  instance:
    hostname: 192.168.0.12
  client:
    service-url:
      defaultZone: http://192.168.0.12:8761/eureka/
server:
  port: 8762

spring:
  boot:
    admin:
      client:
        url: "http://192.168.137.73:5000"