eureka:
  instance:
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.137.73
  client:
    service-url:
      defaultZone: http://192.168.137.73:8761/eureka/
server:
  port: 5002
spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: "http://192.168.137.73:5000"
  application:
    name: sleuth-user-service
  zipkin:
    base-url: http://192.168.137.73:9411
  sleuth:
    sampler:
      probability: 1.0
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: "logs/${spring.application.name}.log"