spring:
  application:
    name: eureka-ribbon-client

server:
  port: 8764

eureka:
  client:
    service-url:
      defaultZone: http://192.168.137.73:8761/eureka/
  instance:
    hostname: 192.168.137.73
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
