eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://192.168.137.73:8761/eureka/
server:
  port: 8762
logging:
  file: "logs/eureka-client-one.log"
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  boot:
    admin:
      client:
        url: "http://192.168.137.73:5000"
  application:
    name: eureka-client-one