spring:
  application:
    name: peer1
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false # 中小规模下，自我保护模式坑比好处多，所以关闭它
    eviction-interval-timer-in-ms: 5000 # 续期时间，即扫描失效服务的间隔时间（缺省为60*1000ms）从服务列表中剔除
    use-read-only-response-cache: false       # 禁用readOnlyCacheMap
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.137.21
  client:
    service-url:
      defaultZone: http://192.168.137.31:${server.port}/eureka/,http://192.168.137.41:${server.port}/eureka/
