eureka:
  instance:
    ip-address: 192.168.137.73
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true #开启自己作为客户端注册，这样在别的集群中也能看见自己
    fetch-registry: false
    service-url:
      defaultZone: http://192.168.137.73:8761/eureka/
server:
  port: 8761

spring:
  boot:
    admin:
      client:
        url: "http://192.168.137.73:5000"