server:
  port: 8761
eureka:
  instance: #如果只是配置了eureka.instance.prefer-ip-address=true，而不配置eureka.instance.instance-id,那还是显示localhost，但ip地址是可以访问得了
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.137.73
  client:
    register-with-eureka: true #开启自己作为客户端注册，这样在别的集群中也能看见自己
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: "http://192.168.137.73:5000"
  application:
    name: eureka-server
logging:
  file: "logs/${spring.application.name}.log"