spring:
  application:
    name: peer3
server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.137.41
  client:
    service-url:
      defaultZone: http://192.168.137.21:${server.port}/eureka/,http://192.168.137.31:${server.port}/eureka/
