spring:
  application:
    name: peer2
server:
  port: 8761
eureka:
  instance:
    hostname: 192.168.137.31
  client:
    service-url:
      defaultZone: http://192.168.137.21:${server.port}/eureka/,http://192.168.137.41:${server.port}/eureka/
