spring:
  application:
    name: eureka-turbine-client
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: "http://192.168.81.110:5000"
server:
  port: 8769
turbine:
  aggregator:
    cluster-config: default
  app-config: eureka-ribbon-client,eureka-feign-client
  cluster-name-expression: new String("default")
eureka:
  client:
    # 向注册中心注册
    fetch-registry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.81.110:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.81.110
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: "logs/${spring.application.name}.log"