#spring:
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native
#  application:
#    name: config-server
#server:
#  port: 8769

server:
  port: 8767
spring:
  profiles:
    active: dev
  boot:
    admin:
      client:
        url: "http://192.168.81.110:5000"
  cloud:
    config:
      server:
        git:
          uri: http://192.168.3.233/nanjing-springcloud/applicationconfig.git #仓库地址
          search-paths: dev #仓库下的子目录
          username: root #gitlab用户名
          password: MECT888! #gitlab密码
  #通过/{application}/{profile}就能访问配置文件
  #application表示配置文件的名字，对应我们上面的配置文件就是application(配置文件统一前缀)
  #profile表示环境(配置文件后面的文件名)
  #举例：启动配置中心后通过访问：http://192.168.81.110:8767/application/test/即可访问配置文件内容
  application:
    name: config-server
eureka:
  instance:
    lease-renewal-interval-in-seconds: 5      # 心跳时间，即服务续约间隔时间（缺省为30s）
    lease-expiration-duration-in-seconds: 10  # 没有心跳的淘汰时间，10秒，即服务续约到期时间（缺省为90s）
    hostname: ${eureka.instance.ip-address}
    instance-id: ${eureka.instance.ip-address}:${server.port}
    prefer-ip-address: true
    ip-address: 192.168.81.110
  client:
    # 向注册中心注册
    fetch-registry: true
    # 服务清单的缓存更新时间，默认30秒一次
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://192.168.81.110:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
logging:
  file: "logs/${spring.application.name}.log"
